import T from "T";

export const VIEW_PERMISSION = "view";
export const ADD_PERMISSION = "add";
export const EDIT_PERMISSION = "edit";
export const DELETE_PERMISSION = "delete";

const { CREATOR, LISTENER, VIEW, ADD, EDIT, DELETE } = T;

export const ALL_PERMISSION_KEYS = {
  CREATOR_VIEW_KEY: "creator_view",
  CREATOR_ADD_KEY: "creator_add",
  CREATOR_EDIT_KEY: "creator_edit",
  CREATOR_DELETE_KEY: "creator_delete",
  LISTENER_VIEW_KEY: "listener_view",
  LISTENER_ADD_KEY: "listener_add",
  LISTENER_EDIT_KEY: "listener_edit",
  LISTENER_DELETE_KEY: "listener_delete",
};

// export const ROLES_MAPPING = {
//   [DASHBOARD]: "dashboard",
//   [REPORTS]: "report",
//   [MEMBERS]: "user",
//   [NON_COMPLIANCE]: "nc",
//   [ROLES]: "role",
//   [MASTER_SETTINGS]: "master",
//   [ACCOUNTING]: "accounting",
//   [PRE_SALES]: "pre_sales",
//   [TRAINING]: "training",
//   [CASE_STUDY]: "casestudy",
//   [TESTIMONIAL]: "testimonial",
// };

// export const ROLES_PERMISSIONS = {
//   [DASHBOARD]: [VIEW_PERMISSION],
//   [REPORTS]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   [MEMBERS]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   [NON_COMPLIANCE]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION, PM_FILTER_PERMISSION],
//   [ROLES]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   [MASTER_SETTINGS]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   [ACCOUNTING]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   [PRE_SALES]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   [TRAINING]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   // [CASE_STUDY]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
//   // [TESTIMONIAL]: [VIEW_PERMISSION, ADD_PERMISSION, EDIT_PERMISSION, DELETE_PERMISSION],
// };

// export const TABLE_HEADER_VALUES = [PERMISSIONS, VIEW, ADD, EDIT, DELETE, PM_FILTER];
